FROM nginx:alpine@sha256:5616878291a2eed594aee8db4dade5878cf7edcb475e59193904b198d9b830de

RUN apk add --update --no-cache bash=5.3.3-r1 nodejs=24.14.1-r0

ARG PORT=8080
ARG AUTOENV_OUTPUT_DIR=/usr/share/nginx/autoenv
ARG AUTOENV_OUTPUT_FILENAME=autoenv.json
ARG AUTOENV_HTTP_PATH=/__autoenv
ARG NGINX_CONF_PATH=/etc/nginx/nginx.conf
ARG AUTOENV_INJECT_HTML=true
ARG AUTOENV_GLOBAL_VAR=window.__CONFIG__
ARG AUTOENV_HTML_SEARCH_PATH=/app

ENV PORT=${PORT}

ENV AUTOENV_OUTPUT_DIR=${AUTOENV_OUTPUT_DIR}
ENV AUTOENV_OUTPUT_FILENAME=${AUTOENV_OUTPUT_FILENAME}
ENV AUTOENV_FS_PATH=${AUTOENV_OUTPUT_DIR}/${AUTOENV_OUTPUT_FILENAME}
ENV AUTOENV_HTTP_PATH=${AUTOENV_HTTP_PATH}
ENV NGINX_CONF_PATH=${NGINX_CONF_PATH}
ENV AUTOENV_INJECT_HTML=${AUTOENV_INJECT_HTML}
ENV AUTOENV_GLOBAL_VAR=${AUTOENV_GLOBAL_VAR}
ENV AUTOENV_HTML_SEARCH_PATH=${AUTOENV_HTML_SEARCH_PATH}
ENV ENVIRONMENT=production

ENV TEMPLATE_DIR=/autoenv/templates
RUN mkdir ${AUTOENV_OUTPUT_DIR} && mkdir /autoenv

WORKDIR /autoenv

COPY . .

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "/autoenv/healthcheck.sh" ]

ENTRYPOINT [ "/autoenv/entrypoint.sh" ]
